name: HCI Website Deployment
run-name: ${{ github.actor }} is running the deployment 🚀
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm grunt

      - uses: burnett01/rsync-deployments@5.2.1
        name: Rsync deployment
        with: 
          switches: -avzr
          path: build/
          remote_path: ${{ secrets.RAS_DEPLOY_PATH }}
          remote_host: ${{ secrets.RAS_DEPLOY_HOST }}
          remote_user: ${{ secrets.RAS_DEPLOY_USER }}
          remote_key: ${{ secrets.RAS_DEPLOY_KEY }}
